<?php

function wconsumer_menu() {
	$items['wconsumer/service/callback'] = array(
    // A type of MENU_CALLBACK means leave the path completely out of the menu
    // links.
    'type' => MENU_CALLBACK,
    // The title is still used for the page title, even though it's not used
    // for the menu link text, since there's no menu link.
    'title' => 'Callback Only',
    'page callback' => '_wconsumer_callback',

    'access callback' => TRUE,
  );
  return $items;
}

function _wconsumer_callback() {
	
	$response = $_GET;
	drupal_set_message(t('Something @var just happened.', array('@var' => print_r($response, TRUE))), 'butterflies'); 
	return $response;
}