<?php
/**
 * @file
 * Web Consumer Manager Base
 *
 * @package  wconsumer
 * @subpackage  wc_api
 * @link https://github.com/kaw393939/wconsumer/
 */

use Drupal\wconsumer\Service;
use Guzzle\Http\Client;

function wconsumer_init() {
  // Create a client and provide a base URL
  return;
  $client = new Client('https://api.github.com');
  // Create a request with basic Auth
  $request = $client->get('/user')->setAuth('srtfisher@gmail.com', 'h76hya');
  // Send the request and get the response
  $response = $request->send();
  echo $response->getBody();
  // >>> {"type":"User", ...
  echo $response->getHeader('Content-Length');
  // >>> 792

  // Create a client to work with the Twitter API
  $client = new Client('https://api.twitter.com/{version}', array(
      'version' => '1.1'
  ));

  // Sign all requests with the OauthPlugin
  $client->addSubscriber(new Guzzle\Plugin\Oauth\OauthPlugin(array(
      'consumer_key'    => '***',
      'consumer_secret' => '***',
      'token'           => '***',
      'token_secret'    => '***'
  )));

  echo $client->get('statuses/user_timeline.json')->send()->getBody();
  // >>> {"public_gists":6,"type":"User" ...

  // Create a tweet using POST
  $request = $client->post('statuses/update.json', null, array(
      'status' => 'Tweeted with Guzzle, http://guzzlephp.org'
  ));

  // Send the request and parse the JSON response into an array
  $data = $request->send()->json();
  echo $data['text'];

  $service = array();
  return;
  drupal_set_message('<pre>' . print_r(
    Service::services($service), TRUE
  ) . '</pre>');
}


/**
 * Unit Testing on Web Consumer
 */
function wconsumer_simpletest() {
  $dir = drupal_get_path('module', 'wconsumer'). '/tests';
  $tests = file_scan_directory($dir, '\.test$');
  return array_keys($tests);
}

/**
 * Register the Namespace for this project
 * 
 * @param object
 * @return void
 * @access private
 */
function wconsumer_xautoload($api)
{
  $api->namespaceRoot('Guzzle');
  $api->namespaceRoot('Symfony');
}
