<?php
function wc_tropo_wc_config($config) {
  $config['service'] = array(
    'tropo' => array(
      'name' => 'tropo',
      'authMethod' => 'apiKey',
      'apiKey' => '1234',
      'serviceAffinity' => 'site', // vs 'user'
      'affinityProps' => array(
      //Optional menu function to call when using this service
      //	      'menu_callback'              => 'callback_functionName',
        )
    )
  );
  return $config;
}