<?php
/**
 * @file Sample Module
 */

function wc_sample_wc_config($config) {
  // Setup the form fields that it will ask
  // 
  // Some APIs require that you pass a username as the HTTP username
  // and the API key as the password. Others require just the password.
  // 
  // It is flexible to how you want it.
  
  $formFields = array();

  // Ask for the HTTP username
  // The array key is arbitrary. However if you change it, it will affect
  // the stored information.
  $formFields['username'] = array(
    // Identity what this is (the HTTP username)
    'as' => 'http-username',

    // UI label for the settings form
    'label' => 'Username',

    'default' => '',

    // Will default to TRUE
    'required' => TRUE,
  );

  $formFields['api-key'] = array(
    // Identify what this really is to your requests
    'as' => 'http-password',

    // UI label for the settings form
    'label' => 'API Key',
  );

  // In the case of an HTTP header, the array key here is the name of the header we will be passing
  $formFields['x-api-key'] = array(
    // Identify what this really is to your requests
    'as' => 'http-header',

    // UI label for the settings form
    'label' => 'Optional Header',

    'default' => '',

    // Will default to TRUE
    'required' => FALSE,
  );

  // Setup the service now...
  $config['service'] = array(
    'sample' => array(
      'name' => 'sample',
      'applicationCreateURL' => 'http-//njit.edu/',
      'apiBase' => 'http-//njit.edu/api/',

      // Specify that is is using API Key Authentication
      'authMethod' => 'apikey',

      // Add the Authentication Methods
      'formFields' => $formFields,
    ),
  );
  return $config;
}
